# Generated by Django 2.2.17 on 2021-01-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='homepage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
